### ISSUE TITLE
error with arguments in sns.barplot()

### ISSUE THREAD

**Issue by naveeagrawal** [GokuMohandas/mlops-course#25]
Error with arguments in sns.barplot() in EDA section.

https://github.com/GokuMohandas/mlops-course/blob/main/notebooks/tagifai.ipynb

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-8-04febc749597>](https://localhost:8080/#) in <cell line: 4>()
      2 tags, tag_counts = zip(*Counter(df.tag.values).most_common())
      3 plt.figure(figsize=(10, 3))
**----> 4 ax = sns.barplot(list(tags), list(tag_counts))**
      5 plt.title("Tag distribution", fontsize=20)
      6 plt.xlabel("Tag", fontsize=16)

TypeError: barplot() takes from 0 to 1 positional arguments but 2 were given

the seaborn version in the colab notebook is 0.12.2

**Comment by naveeagrawal** [comment]
the error could be resolved by replacing 
`ax = sns.barplot(list(tags), list(tag_counts))`
with
`ax = sns.barplot(x=list(tags), y=list(tag_counts))`

**Comment by GokuMohandas** [comment]
hey @naveeagrawal, thanks for sharing this. A few others brought this up [too](https://github.com/GokuMohandas/Made-With-ML/issues/220) and it's due to Colab auto-upgrading their packages every so often (seaborn api changed). I was going to push the change but have a lot of changes coming soon so decided to wait. Also we won't be using Google colab anymore because it essentially causes projects like this to break every few months.
